# Generated by Django 5.2.10 on 2026-01-26 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(help_text='Network name (max 32 chars per WiFi spec)', max_length=32, unique=True)),
                ('security_type', models.CharField(choices=[('open', 'Open'), ('wep', 'WEP'), ('wpa', 'WPA'), ('wpa2', 'WPA2'), ('wpa3', 'WPA3'), ('wpa2_enterprise', 'WPA2 Enterprise'), ('wpa3_enterprise', 'WPA3 Enterprise')], default='wpa2', max_length=20)),
                ('password', models.CharField(blank=True, help_text='PSK password (8-63 chars for WPA)', max_length=63)),
                ('auto_connect', models.BooleanField(default=True, help_text='Automatically connect when in range')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority networks connect first')),
                ('hidden', models.BooleanField(default=False, help_text='Network does not broadcast SSID')),
                ('bssid', models.CharField(blank=True, help_text='MAC address of specific AP (XX:XX:XX:XX:XX:XX)', max_length=17)),
                ('metered', models.BooleanField(default=False, help_text='Treat as metered connection')),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saved Network',
                'verbose_name_plural': 'Saved Networks',
                'ordering': ['-priority', '-last_connected'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('failed', 'Connection Failed'), ('auth_failed', 'Authentication Failed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signal_strength', models.IntegerField(blank=True, help_text='Signal strength 0-100', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('bssid', models.CharField(blank=True, help_text='AP MAC address connected to', max_length=17)),
                ('error_message', models.TextField(blank=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to='wifi.savednetwork')),
            ],
            options={
                'verbose_name': 'Connection Log',
                'verbose_name_plural': 'Connection Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
