# Generated by Django 5.2.10 on 2026-01-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=64)),
                ('connection', models.CharField(max_length=64)),
                ('mac_address', models.CharField(blank=True, max_length=64, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
