# Generated by Django 5.2.10 on 2026-01-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='physical_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
