# Generated by Django 5.2.10 on 2026-01-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('cpu', 'CPU'), ('ram', 'RAM'), ('swap', 'Swap'), ('disk', 'Disk'), ('gpu_util', 'GPU Utilization'), ('gpu_mem', 'GPU Memory')], max_length=20)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('value', models.FloatField()),
                ('threshold', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
